<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/modal",
        'mage/backend/notification',
        "prototype"
    ], function($, modal, notification) {

//<![CDATA[
        Window.keepMultiModalWindow = true;
        var itemsView = {
            overlayShowEffectOptions : null,
            overlayHideEffectOptions : null,
            modal: null,
            open : function(viewUrl, elementId) {
                if (viewUrl && elementId) {
                    $.ajax({
                        url: viewUrl,
                        data: {
                            id: elementId
                        },
                        showLoader: true,
                        dataType: 'html',
                        success: function(data, textStatus, transport) {
                            this.openDialogWindow(data, elementId);
                        }.bind(this)
                    });
                }
            },
            openDialogWindow : function(data, elementId) {

                var self = this;
                if (this.modal) {
                    this.modal.html($(data).html());
                } else {
                    var options = {
                        title: '<?= /* @noEscape */ __('Item View'); ?>',
                        modalClass: 'magento',
                        type: 'slide',

                        buttons: [{
                            text: $.mage.__('Close'),
                            class: 'action- scalable back',
                            click: function () {
                                self.closeDialogWindow(this);
                            }
                        }],
                        close: function () {
                            self.closeDialogWindow(this);
                        }
                    };
                    this.modal = $(data).modal(options);
                }
                this.modal.modal('openModal');
            },
            closeDialogWindow : function(dialogWindow) {
                $('body').trigger('processStop');
                dialogWindow.closeModal();
                Windows.overlayShowEffectOptions = this.overlayShowEffectOptions;
                Windows.overlayHideEffectOptions = this.overlayHideEffectOptions;
            }
        };
        window.itemsView = itemsView;
//]]>
    });</script>