<?php /* @var $block \Ced\ConnectBase\Block\Adminhtml\Wizard\Steps\SourceOnboarding */ ?> <?= $block->getChildHtml(); ?> <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= /* @noEscape */  $block->getComponentName() ?>": {
                        "component": "Ced_ConnectBase/js/wizard/steps/source_onboarding",
                        "readyToRenderNextStep": "<?= /* @noEscape */  $block->getIsStepConfigured() ?>",
                        "appendTo": "<?= /* @noEscape */  $block->getParentComponentName() ?>"
                    }
                }
            }
        }
    }</script>