<?php /** * @var $block \Ced\ConnectBase\Block\Adminhtml\Account\ModalBox */ $accounts = $block->getMarketplaceAccounts(); $accountId = null; if ($accounts->getSize() == 1) { $accountId = $accounts->getFirstItem()->getId(); } ?> <div id="popup-modal" style="display: none"><div class="field-wrapper" style="position: relative;"><select id="accounts" name="accounts" title="<?= /* @noEscape */ $block->escapeHtml($block->escapeHtml(__('Accounts'))) ?>" class="admin__control-select"><option value=""><?= /* @noEscape */ $block->escapeHtml(__('Please Select')) ?></option><?php foreach ($accounts as $account) { ?> <?php if ($account->getId()) { ?> <option value="<?= $block->escapeHtml($account->getId()) ?>"><?= /* @noEscape */ $block->escapeHtml(__($account->getTitle())) ?></option><?php } ?> <?php } ?></select> <div class="error" style="position:absolute; color: red; display: none"> Please Select an account</div></div></div><script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {

            $('#accounts').on('click', function () {
                $('.error').hide()
            });

            let options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Select Account',
                modalClass: 'custom-modal',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: 'continue-to-category-form',
                    click: function () {
                        let url = '<?= /* @noEscape */ $block->escapeHtml($block->getTargetFormUrl())?>'
                        let selectedAccount = $('#accounts').val();
                        console.log('Selected : ',selectedAccount);
                        if (selectedAccount !== '' && selectedAccount !== null) {
                            url = url + 'account/' + selectedAccount;
                            this.closeModal();
                            window.location.replace(url);
                        } else {
                            $('.error').show()
                        }
                    }
                }]
            };

            modal(options, $('#popup-modal'));
            $("#ced-add-new-category-template").click(function() {
                let account = '<?= /* @noEscape */ $accountId ?>';
                if (account) {
                    let url = '<?= /* @noEscape */ $block->escapeHtml($block->getTargetFormUrl())?>';
                    url = url + 'account/' + account;
                    window.location.replace(url);
                } else {
                    $("#popup-modal").modal('openModal');
                }
            });
        }

    );</script>